### ISSUE TITLE
`~` is not expanded for files

### ISSUE THREAD

**Issue by fdw** [fdw/rofimoji#136]
I have `~/.config/rofimoji.rc`:
```
files = [emojis, nerd_font, arrows, ~/.local/share/rofimoji/latipun.csv]
skin-tone = neutral
```

It works on v5.6.0, but has this error on v6.0.0:
```sh
❯ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 46, in __open_main_selector_window
    read_characters_from_files(self.args.files, load_frecent_characters(), self.args.use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 14, in read_characters_from_files
    for file in __resolve_all_filenames(files, use_additional):
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 26, in __resolve_all_filenames
    resolved_file_names += __resolve_filename(file_name, use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 54, in __resolve_filename
    raise FileNotFoundError(f"Couldn't find file {file_name!r}")
FileNotFoundError: Couldn't find file '~/.local/share/rofimoji/latipun.csv'
```

but, if I run directly using command line, it works.
```sh

❯ rofimoji --files emojis nerd_font arrows ~/.local/share/rofimoji/latipun.csv
# works here
```

**EDIT:**
with this config, error occurred when running from terminal:
```
files = [emojis, nerd_font, arrows, .local/share/rofimoji/*.csv]
skin-tone = neutral
```

error:
```sh
❯ rofimoji
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
  File "/usr/lib/python3.10/site-packages/picker/standalone.py", line 46, in __open_main_selector_window
    read_characters_from_files(self.args.files, load_frecent_characters(), self.args.use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 14, in read_characters_from_files
    for file in __resolve_all_filenames(files, use_additional):
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 26, in __resolve_all_filenames
    resolved_file_names += __resolve_filename(file_name, use_additional)
  File "/usr/lib/python3.10/site-packages/picker/file_loader.py", line 54, in __resolve_filename
    raise FileNotFoundError(f"Couldn't find file {file_name!r}")
FileNotFoundError: Couldn't find file '.local/share/rofimoji/*.csv'
```

_Originally posted by @latipun7 in https://github.com/fdw/rofimoji/issues/134#issuecomment-1303101280_

**Comment by fdw** [comment]
The problem is that `~` is not expanded. I'm not even sure if that was done on purpose in the previous versions 😉

I've pushed a possible fix to `main`, so could you please try that?

**Comment by latipun7** [comment]
Nice, it works 👍 glob also works.
```
files = [emojis, nerd_font, arrows, ~/.local/share/rofimoji/*.csv]
```

**Comment by fdw** [comment]
Perfect, thanks 🙂
