### ISSUE TITLE
Rofimoji errors out upon selecting an emoji when run with rofi

### ISSUE THREAD

**Issue by rew1nter** [fdw/rofimoji#145]
Running rofimoji directly works but when I run with rofi this way:
```bash
rofi -modi "emoji:$(which rofimoji)" -show emoji
``` 
I get the following error after clicking enter on an emoji:
```python
Traceback (most recent call last):
  File "/home/crusader/.local/bin/rofimoji", line 8, in <module>
    sys.exit(main())
  File "/home/crusader/.local/lib/python3.10/site-packages/picker/__main__.py", line 11, in main
    ModeRofimoji().mode()
  File "/home/crusader/.local/lib/python3.10/site-packages/picker/mode.py", line 107, in mode
    self.execute_actions(state)
  File "/home/crusader/.local/lib/python3.10/site-packages/picker/mode.py", line 217, in execute_actions
    execute_action(state.processed_characters, state.actions)
  File "/home/crusader/.local/lib/python3.10/site-packages/picker/action.py", line 20, in execute_action
    typer.type_characters(characters, active_window)
  File "/home/crusader/.local/lib/python3.10/site-packages/picker/typer/typer.py", line 48, in type_characters
    run(["xdotool", "windowactivate", "--sync", active_window, "type", "--clearmodifiers", characters])
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1778, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by fdw** [comment]
Which version of `rofimoji` are you running? Which character are you trying to type?

**Comment by rew1nter** [comment]
`rofimoji 6.1.0`
This happens regardless of what character I use

**Comment by rew1nter** [comment]
I think I fixed it partially. Runnning with rofi like this doesn't cause any error and copies to clipboard
```rofi -modi "emoji:$(which rofimoji) --action copy --clipboarder xclip" -show emoji ```

**Comment by fdw** [comment]
Ah, yes, `rofimoji` [cannot type directly when run as a mode](https://github.com/fdw/rofimoji#caveats-when-running-rofimoji-as-a-rofi-mode), sorry. That's just how `rofi` works.
