### ISSUE TITLE
KeyError in select_skin_tone

### ISSUE THREAD

**Issue by The-Compiler** [fdw/rofimoji#16]
When I select the thumbs up emoji, rofimoji crashes with:

```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 1905, in <module>
    emojis = compile_chosen_emojis(stdout.splitlines(), args.skin_tone[0])
  File "/usr/bin/rofimoji", line 1870, in compile_chosen_emojis
    emoji = select_skin_tone(emoji, skin_tone)
  File "/usr/bin/rofimoji", line 1756, in select_skin_tone
    return selected_emoji + fitzpatrick_modifiers_reversed[skin_tone]
KeyError: 'a'
```

I'm running 0f81d64 with rofi 1.5.4 on Archlinux. The 2.1.0 release seems to work fine.

**Comment by fdw** [comment]
Thanks for finding and immediately fixing that bug! 😄
