### ISSUE TITLE
`tofi` not working?

### ISSUE THREAD

**Issue by 42Willow** [fdw/rofimoji#174]
When I try to run rofimoji with only tofi installed as an option for a picker I get:
```
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.11/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/standalone.py", line 44, in __open_main_selector_window
    return self.selector.show_character_selection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/selector/selector.py", line 36, in show_character_selection
    raise NoSelectorFoundException()
picker.selector.selector.NoSelectorFoundException: Could not find a valid way to show the selection. Please check the required dependencies.
```

**Comment by fdw** [comment]
Okay... what does `which tofi` return on the terminal?

**Comment by 42Willow** [comment]
`/usr/bin/tofi`

**Comment by fdw** [comment]
Which version of `rofimoji` do you use?

**Comment by 42Willow** [comment]
I'm on `6.2.0`. Sorry I should have provided that at the start.

**Comment by 42Willow** [comment]
Oops, that's the issue then. Thanks.

**Comment by 42Willow** [comment]
Never mind, just installed `rofimoji` from git. (`aur/rofimoji-git`)

Same error:
```
❯ rofimoji --selector tofi
Traceback (most recent call last):
  File "/usr/bin/rofimoji", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/__main__.py", line 9, in main
    StandaloneRofimoji().standalone()
  File "/usr/lib/python3.11/site-packages/picker/standalone.py", line 25, in standalone
    action, value = self.__open_main_selector_window()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/standalone.py", line 44, in __open_main_selector_window
    return self.selector.show_character_selection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/picker/selector/tofi.py", line 40, in show_character_selection
    return DEFAULT(), [self.extract_char_from_input(list(characters)[int(tofi.stdout.strip())])]
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

**Comment by fdw** [comment]
This is not expected. Did you choose a character in `tofi`?

**Comment by 42Willow** [comment]
No, tofi didn't even appear...

**Comment by fdw** [comment]
I just tested it, and apparently the parameters of `tofi` have changed since the original implementation in `rofimoji`. (Or I completely messed it up 🙈)

Can you please test the `main` branch; it should be fixed now.

**Comment by 42Willow** [comment]
It's fixed now, thanks!
