### ISSUE TITLE
Commit a6fe835 appears to break rofi mode

### ISSUE THREAD

**Issue by IndigoLily** [fdw/rofimoji#176]
As of a6fe835534b4d22ca089b39eb6113238f851e036, when launched via `rofi -modi "emoji:rofimoji" -show emoji`, the menu shows nothing, and stdout prints

    Traceback (most recent call last):
      File "/usr/bin/rofimoji", line 8, in <module>
        sys.exit(main())
                 ^^^^^^
      File "/usr/lib/python3.11/site-packages/picker/__main__.py", line 11, in main
        ModeRofimoji().mode()
      File "/usr/lib/python3.11/site-packages/picker/mode.py", line 99, in mode
        self.show_characters(state)
      File "/usr/lib/python3.11/site-packages/picker/mode.py", line 129, in show_characters
        self.__format_characters(
      File "/usr/lib/python3.11/site-packages/picker/mode.py", line 146, in __format_characters
        return [f"{key} {value}" for key, value in characters.items() if value != ""]
                                                   ^^^^^^^^^^^^^^^^
    AttributeError: 'list' object has no attribute 'items'

The error on 5674e037b90f8fbe15ce5ae745a2407124b7a12d is exactly the same (except with the line numbers slightly different). It works fine on the previous commit (100ba3dd60dde40ad93ca3a4cf396a9951390939).

In case it's important, I'm on Arch, and I installed rofimoji through the `rofimoji-git` package on the AUR.

**Comment by fdw** [comment]
Thank you! Should be fixed now.
